Models/Butterfly.cs
using ButterfliesShop.Validators;
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;

namespace ButterfliesShop.Models
{
    [ButterflyValidation]
    public class Butterfly
    {
        public int Id { get; set; }

        [Display(Name = "Butterfly name:")]
        [Required]
        public string CommonName { get; set; }

        [Display(Name = "Butterfly family:")]
        public Family? ButterflyFamily { get; set; }

        [Display(Name = "Quantity:")]
        public int? Quantity { get; set; }

        [Display(Name = "Characteristics:")]
        public string Characteristics { get; set; }

        public DateTime CreatedDate { get; set; }

        public string ImageMimeType { get; set; }

        public string ImageName { get; set; }

        [Display(Name = "Photo:")]
        [Required]
        public IFormFile Photo { get; set; }
    }
}

Models/Family.cs
namespace ButterfliesShop.Models
{
    public enum Family
    {
        Grassland,
        Nymphalidae,
        Danaine,
        Riodinidae
    }
}

ViewModels/Butterfly/IndexViewModel.cs
using System.Collections.Generic;

namespace ButterfliesShop.ViewModels.Butterfly
{
    public class IndexViewModel
    {
        public IEnumerable<Models.Butterfly> Butterflies { get; set; }
    }
}

Controllers/ButterflyController.cs
using ButterfliesShop.Models;
using ButterfliesShop.Services;
using ButterfliesShop.ViewModels.Butterfly;
using Microsoft.AspNetCore.Mvc;

namespace ButterfliesShop.Controllers
{
    public class ButterflyController : Controller
    {
        private readonly IDataService DataService;
        private readonly IButterfliesQuantityService ButterfliesQuantityService;

        public ButterflyController(
            IDataService dataService,
            IButterfliesQuantityService butterfliesQuantityService)
        {
            DataService = dataService;
            ButterfliesQuantityService = butterfliesQuantityService;
            InitializeButterfliesData();
        }

        public IActionResult Index() => View(new IndexViewModel { Butterflies = DataService.ButterfliesList });

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(Butterfly butterfly)
        {
            if (!ModelState.IsValid || !DataService.AddButterfly(butterfly)) return View(butterfly);
            return RedirectToAction("Index");
        }

        public IActionResult GetImage(int id)
        {
            var butterfly = DataService.GetButterflyById(id);
            if (butterfly == null || string.IsNullOrEmpty(butterfly.ImageName) 
                || string.IsNullOrEmpty(butterfly.ImageMimeType)) return null;

            return File($@"\images\{butterfly.ImageName}", butterfly.ImageMimeType);
        }

        private void InitializeButterfliesData()
        {
            if (DataService.ButterfliesList != null) return;
            var butterflies = DataService.ButterfliesInitializeData();
            foreach (var butterfly in butterflies) ButterfliesQuantityService.AddButterfliesQuantityData(butterfly);
        }
    }
}

Views/Butterfly/Create.cshtml
@model ButterfliesShop.Models.Butterfly
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>

    <div class="container">
        <form method="post" asp-action="Create" enctype="multipart/form-data">
            <div class="form-field">
                <label asp-for="CommonName"></label>
                <input asp-for="CommonName" />
            </div>

            <div class="form-field">
                <label asp-for="ButterflyFamily"></label>
                <select asp-for="ButterflyFamily" 
                        asp-items="Html.GetEnumSelectList<ButterfliesShop.Models.Family>()">
                    <option selected="selected" value="">Select</option>
                </select>
            </div>

            <div class="form-field">
                <label asp-for="Characteristics"></label>
                <input asp-for="Characteristics" />
            </div>

            <div class="form-field">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" />
            </div>

            <div class="form-field">
                <label asp-for="Photo"></label>
                <input asp-for="Photo" type="file" />
            </div>

            <div asp-validation-summary="All"></div>
            
            <div class="form-field">
                <input type="submit" value="Submit" />
            </div>
        </form>
    </div>

</body>
</html>

Views/Butterfly/Index.cshtml
@model ButterfliesShop.ViewModels.Butterfly.IndexViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    
    <div class="container">
        <h1 class="main-title">Butterflies Shop</h1>
        <p class="into">Welcome to our Web Store, Enjoy a Wide Variety of Butterflies</p>
        <p class="into">Our Butterflies in the Shop</p>

        <button type="button" onclick="location.href='@Url.Action("Create", "Butterfly")'">Add</button>
    </div>

    <div class="img-container">
        @foreach (var butterfly in Model.Butterflies)
        {
            <div class="photo-index-card">

                <p>@butterfly.CommonName</p>
                <p>@butterfly.ButterflyFamily</p>
                <p>@butterfly.Quantity</p>
                <p>@butterfly.Characteristics</p>
                <p>@butterfly.CreatedDate</p>

                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", new { id = butterfly.Id })" />
                </div>
            </div>
        }
    </div>

</body>
</html>